<?php
/**
 * MatrixCostingModel
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stadia Maps Geospatial APIs
 *
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.
 *
 * The version of the OpenAPI document: 11.1.0
 * Contact: support@stadiamaps.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MatrixCostingModel Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MatrixCostingModel
{
    /**
     * Possible values of this enum
     */
    public const AUTO = 'auto';

    public const AUTO_TRAFFIC = 'auto_traffic';

    public const AUTO_TRAFFIC_PREMIUM = 'auto_traffic_premium';

    public const BUS = 'bus';

    public const BUS_TRAFFIC = 'bus_traffic';

    public const BUS_TRAFFIC_PREMIUM = 'bus_traffic_premium';

    public const TAXI = 'taxi';

    public const TAXI_TRAFFIC = 'taxi_traffic';

    public const TAXI_TRAFFIC_PREMIUM = 'taxi_traffic_premium';

    public const TRUCK = 'truck';

    public const TRUCK_TRAFFIC = 'truck_traffic';

    public const TRUCK_TRAFFIC_PREMIUM = 'truck_traffic_premium';

    public const BICYCLE = 'bicycle';

    public const BIKESHARE = 'bikeshare';

    public const MOTOR_SCOOTER = 'motor_scooter';

    public const MOTORCYCLE = 'motorcycle';

    public const PEDESTRIAN = 'pedestrian';

    public const LOW_SPEED_VEHICLE = 'low_speed_vehicle';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTO,
            self::AUTO_TRAFFIC,
            self::AUTO_TRAFFIC_PREMIUM,
            self::BUS,
            self::BUS_TRAFFIC,
            self::BUS_TRAFFIC_PREMIUM,
            self::TAXI,
            self::TAXI_TRAFFIC,
            self::TAXI_TRAFFIC_PREMIUM,
            self::TRUCK,
            self::TRUCK_TRAFFIC,
            self::TRUCK_TRAFFIC_PREMIUM,
            self::BICYCLE,
            self::BIKESHARE,
            self::MOTOR_SCOOTER,
            self::MOTORCYCLE,
            self::PEDESTRIAN,
            self::LOW_SPEED_VEHICLE
        ];
    }
}


