<?php
/**
 * OsrmGuidanceModifier
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stadia Maps Geospatial APIs
 *
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.
 *
 * The version of the OpenAPI document: 7.0.0
 * Contact: support@stadiamaps.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OsrmGuidanceModifier Class Doc Comment
 *
 * @category Class
 * @description An optional value indicating the directional change of the maneuver (further clarifying type).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OsrmGuidanceModifier
{
    /**
     * Possible values of this enum
     */
    public const UTURN = 'uturn';

    public const SHARP_RIGHT = 'sharp right';

    public const RIGHT = 'right';

    public const SLIGHT_RIGHT = 'slight right';

    public const STRAIGHT = 'straight';

    public const SLIGHT_LEFT = 'slight left';

    public const LEFT = 'left';

    public const SHARP_LEFT = 'sharp left';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UTURN,
            self::SHARP_RIGHT,
            self::RIGHT,
            self::SLIGHT_RIGHT,
            self::STRAIGHT,
            self::SLIGHT_LEFT,
            self::LEFT,
            self::SHARP_LEFT
        ];
    }
}


